
export const predefinedTeams = [
    // Brasileirão Série A
    { name: 'Athletico-PR', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4289.png' },
    { name: 'Atlético-GO', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4281.png' },
    { name: 'Atlético-MG', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1766.png' },
    { name: 'Bahia', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1779.png' },
    { name: 'Botafogo', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1776.png' },
    { name: 'Corinthians', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1777.png' },
    { name: 'Criciúma', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/6698.png' },
    { name: 'Cruzeiro', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1770.png' },
    { name: 'Cuiabá', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/6684.png' },
    { name: 'Flamengo', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1780.png' },
    { name: 'Fluminense', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1765.png' },
    { name: 'Fortaleza', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4283.png' },
    { name: 'Grêmio', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1773.png' },
    { name: 'Internacional', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1769.png' },
    { name: 'Juventude', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4291.png' },
    { name: 'Palmeiras', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1764.png' },
    { name: 'Red Bull Bragantino', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1771.png' },
    { name: 'São Paulo', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1775.png' },
    { name: 'Vasco da Gama', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1772.png' },
    { name: 'Vitória', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1778.png' },

    // Brasileirão Série B
    { name: 'Amazonas', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Amazonas_Futebol_Clube_2023.svg' },
    { name: 'América-MG', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1767.png' },
    { name: 'Avaí', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1774.png' },
    { name: 'Botafogo-SP', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6682.png' },
    { name: 'Brusque', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6699.png' },
    { name: 'Ceará', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4282.png' },
    { name: 'Chapecoense', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4300.png' },
    { name: 'Coritiba', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1768.png' },
    { name: 'CRB', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4299.png' },
    { name: 'Goiás', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4285.png' },
    { name: 'Guarani', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4294.png' },
    { name: 'Ituano', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6688.png' },
    { name: 'Mirassol', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/MirassolFutebolClube.png' },
    { name: 'Novorizontino', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6692.png' },
    { name: 'Operário-PR', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Operario-pr.png' },
    { name: 'Paysandu', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Paysandu_sport_club.png' },
    { name: 'Ponte Preta', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4298.png' },
    { name: 'Santos', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1783.png' },
    { name: 'Sport Recife', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1781.png' },
    { name: 'Vila Nova', type: 'club', countryOrConfederation: 'CONMEBOL / Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4293.png' },

    // Premier League & FA Cup
    { name: 'Arsenal FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/57.svg' },
    { name: 'Aston Villa FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/58.svg' },
    { name: 'AFC Bournemouth', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/1044.svg' },
    { name: 'Brentford FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/402.svg' },
    { name: 'Brighton & Hove Albion FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/397.svg' },
    { name: 'Chelsea FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/61.svg' },
    { name: 'Crystal Palace FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/354.svg' },
    { name: 'Everton FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/62.svg' },
    { name: 'Fulham FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/63.svg' },
    { name: 'Ipswich Town FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/349.svg' },
    { name: 'Leicester City FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/338.svg' },
    { name: 'Liverpool FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/64.svg' },
    { name: 'Manchester City FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/65.svg' },
    { name: 'Manchester United FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/66.svg' },
    { name: 'Newcastle United FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/67.svg' },
    { name: 'Nottingham Forest FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/345.svg' },
    { name: 'Southampton FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/340.svg' },
    { name: 'Tottenham Hotspur FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/73.svg' },
    { name: 'West Ham United FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/563.svg' },
    { name: 'Wolverhampton Wanderers FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/76.svg' },
    
    // EFL Championship (Série B Inglesa)
    { name: 'Blackburn Rovers FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/60.svg' },
    { name: 'Bristol City FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/387.svg' },
    { name: 'Burnley FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/328.svg' },
    { name: 'Coventry City FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/335.svg' },
    { name: 'Derby County FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/343.svg' },
    { name: 'Hull City AFC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/322.svg' },
    { name: 'Leeds United FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/347.svg' },
    { name: 'Luton Town FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/341.svg' },
    { name: 'Millwall FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/69.svg' },
    { name: 'Norwich City FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/342.svg' },
    { name: 'Queens Park Rangers FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/349.svg' },
    { name: 'Sheffield United FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/356.svg' },
    { name: 'Sheffield Wednesday FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/344.svg' },
    { name: 'Sunderland AFC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/71.svg' },
    { name: 'West Bromwich Albion FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/74.svg' },
    
    // League One (Inglaterra)
    { name: 'Birmingham City FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'League One', crestUrl: 'https://crests.football-data.org/59.svg' },
    { name: 'Huddersfield Town AFC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'League One', crestUrl: 'https://crests.football-data.org/385.svg' },
    { name: 'Bristol Rovers FC', type: 'club', countryOrConfederation: 'UEFA / Inglaterra', league: 'League One', crestUrl: 'https://crests.football-data.org/388.svg' },

    // La Liga
    { name: 'Deportivo Alavés', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/263.svg' },
    { name: 'Athletic Club', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/77.svg' },
    { name: 'Club Atlético de Madrid', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/78.svg' },
    { name: 'FC Barcelona', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/81.svg' },
    { name: 'RC Celta de Vigo', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/558.svg' },
    { name: 'RCD Espanyol de Barcelona', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/82.svg' },
    { name: 'Getafe CF', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/82.svg' },
    { name: 'Girona FC', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/298.svg' },
    { name: 'UD Las Palmas', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/279.svg' },
    { name: 'CD Leganés', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/299.svg' },
    { name: 'RCD Mallorca', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/89.svg' },
    { name: 'CA Osasuna', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/79.svg' },
    { name: 'Rayo Vallecano', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/87.svg' },
    { name: 'Real Betis Balompié', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/90.svg' },
    { name: 'Real Madrid CF', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/86.svg' },
    { name: 'Real Sociedad de Fútbol', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/92.svg' },
    { name: 'Sevilla FC', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/559.svg' },
    { name: 'Valencia CF', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/95.svg' },
    { name: 'Real Valladolid CF', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/250.svg' },
    { name: 'Villarreal CF', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/94.svg' },
    { name: 'Elche CF', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'Segunda División', crestUrl: 'https://crests.football-data.org/285.svg' },
    { name: 'Granada CF', type: 'club', countryOrConfederation: 'UEFA / Espanha', league: 'Segunda División', crestUrl: 'https://crests.football-data.org/83.svg' },

    // Serie A (Itália)
    { name: 'Atalanta BC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/102.svg' },
    { name: 'Bologna FC 1909', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/103.svg' },
    { name: 'Cagliari Calcio', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/104.svg' },
    { name: 'Como 1907', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/471.svg' },
    { name: 'Empoli FC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/107.svg' },
    { name: 'ACF Fiorentina', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/99.svg' },
    { name: 'Genoa CFC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/108.svg' },
    { name: 'Hellas Verona FC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/450.svg' },
    { name: 'FC Internazionale Milano', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/108.svg' },
    { name: 'Juventus FC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/109.svg' },
    { name: 'SS Lazio', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/110.svg' },
    { name: 'US Lecce', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/445.svg' },
    { name: 'AC Milan', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/98.svg' },
    { name: 'AC Monza', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/5890.svg' },
    { name: 'SSC Napoli', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/113.svg' },
    { name: 'Parma Calcio 1913', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/114.svg' },
    { name: 'AS Roma', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/100.svg' },
    { name: 'Torino FC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/115.svg' },
    { name: 'Udinese Calcio', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/112.svg' },
    { name: 'Venezia FC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/454.svg' },
    { name: 'Frosinone Calcio', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie B', crestUrl: 'https://crests.football-data.org/472.svg' },
    { name: 'US Cremonese', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie B', crestUrl: 'https://crests.football-data.org/457.svg' },
    { name: 'Pisa SC', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie B', crestUrl: 'https://crests.football-data.org/474.svg' },
    { name: 'US Sassuolo Calcio', type: 'club', countryOrConfederation: 'UEFA / Itália', league: 'Serie B', crestUrl: 'https://crests.football-data.org/471.svg' },

    // Bundesliga (Alemanha)
    { name: 'FC Augsburg', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/1.svg' },
    { name: 'Bayer 04 Leverkusen', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/3.svg' },
    { name: 'FC Bayern München', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/5.svg' },
    { name: 'Borussia Dortmund', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/4.svg' },
    { name: 'Borussia Mönchengladbach', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/18.svg' },
    { name: 'Eintracht Frankfurt', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/19.svg' },
    { name: 'SC Freiburg', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/17.svg' },
    { name: 'TSG 1899 Hoffenheim', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/2.svg' },
    { name: 'FC St. Pauli', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/20.svg' },
    { name: 'Holstein Kiel', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/30.svg' },
    { name: 'FSV Mainz 05', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/15.svg' },
    { name: 'RB Leipzig', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/721.svg' },
    { name: 'VfB Stuttgart', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/10.svg' },
    { name: '1. FC Union Berlin', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/28.svg' },
    { name: 'SV Werder Bremen', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/12.svg' },
    { name: 'VfL Wolfsburg', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/11.svg' },
    { name: '1. FC Heidenheim 1846', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: 'Bundesliga', crestUrl: 'https://crests.football-data.org/21.svg' },
    { name: '1. FC Köln', type: 'club', countryOrConfederation: 'UEFA / Alemanha', league: '2. Bundesliga', crestUrl: 'https://crests.football-data.org/1.svg' },

    // Ligue 1 (França)
    { name: 'AS Saint-Étienne', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/527.svg' },
    { name: 'Lille OSC', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/521.svg' },
    { name: 'FC Lorient', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/525.svg' },
    { name: 'Montpellier HSC', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/523.svg' },
    { name: 'FC Nantes', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/547.svg' },
    { name: 'OGC Nice', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/522.svg' },
    { name: 'RC Lens', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/546.svg' },
    { name: 'Stade Brestois 29', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/556.svg' },
    { name: 'Stade Rennais FC', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/529.svg' },
    { name: 'Toulouse FC', type: 'club', countryOrConfederation: 'UEFA / França', league: 'Ligue 1', crestUrl: 'https://crests.football-data.org/543.svg' },
    
    // Liga Portugal
    { name: 'SL Benfica', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/1903.svg' },
    { name: 'FC Porto', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/503.svg' },
    { name: 'Sporting CP', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/507.svg' },
    { name: 'SC Braga', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/502.svg' },
    { name: 'Gil Vicente FC', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/5573.svg' },
    { name: 'CD Nacional', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/5531.svg' },
    { name: 'AVS', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://upload.wikimedia.org/wikipedia/pt/9/91/AVS_Futebol_SAD.png' },
    { name: 'Moreirense FC', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/5615.svg' },
    { name: 'FC Famalicão', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/5575.svg' },
    { name: 'Vitória SC', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/498.svg' },
    { name: 'CD Santa Clara', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/5529.svg' },
    { name: 'Portimonense SC', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/5611.svg' },
    { name: 'Estoril Praia', type: 'club', countryOrConfederation: 'UEFA / Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/496.svg' },
    
    // Argentina
    { name: 'Boca Juniors', type: 'club', countryOrConfederation: 'CONMEBOL / Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2061.svg' },
    { name: 'River Plate', type: 'club', countryOrConfederation: 'CONMEBOL / Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2068.svg' },
    { name: 'Racing Club', type: 'club', countryOrConfederation: 'CONMEBOL / Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2067.svg' },
    { name: 'Independiente', type: 'club', countryOrConfederation: 'CONMEBOL / Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2064.svg' },
    { name: 'San Lorenzo', type: 'club', countryOrConfederation: 'CONMEBOL / Argentina', league: 'Primera División', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Logo_del_Club_Atl%C3%A9tico_San_Lorenzo_de_Almagro.svg' },
    { name: 'Estudiantes', type: 'club', countryOrConfederation: 'CONMEBOL / Argentina', league: 'Primera División', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Escudo_de_Estudiantes_de_La_Plata.svg' },
    
    // MLS
    { name: 'Inter Miami CF', type: 'club', countryOrConfederation: 'CONCACAF / EUA', league: 'MLS', crestUrl: 'https://crests.football-data.org/1607.svg' },
    { name: 'LA Galaxy', type: 'club', countryOrConfederation: 'CONCACAF / EUA', league: 'MLS', crestUrl: 'https://crests.football-data.org/1598.svg' },
    
    // México
    { name: 'Club América', type: 'club', countryOrConfederation: 'CONCACAF / México', league: 'Liga MX', crestUrl: 'https://crests.football-data.org/1620.svg' },
    { name: 'Chivas Guadalajara', type: 'club', countryOrConfederation: 'CONCACAF / México', league: 'Liga MX', crestUrl: 'https://crests.football-data.org/1621.svg' },
    { name: 'Cruz Azul', type: 'club', countryOrConfederation: 'CONCACAF / México', league: 'Liga MX', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cruz_Azul_logo.svg/1200px-Cruz_Azul_logo.svg.png' },
    { name: 'Pumas UNAM', type: 'club', countryOrConfederation: 'CONCACAF / México', league: 'Liga MX', crestUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Pumas_UNAM_logo.svg/1200px-Pumas_UNAM_logo.svg.png' },

    // Outros
    { name: 'Al-Nassr', type: 'club', countryOrConfederation: 'AFC / Arábia Saudita', league: 'Saudi Pro League', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Al-Nassr_FC.svg' },
    { name: 'Al-Hilal', type: 'club', countryOrConfederation: 'AFC / Arábia Saudita', league: 'Saudi Pro League', crestUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Al-Hilal_FC_logo.svg' },

    // Seleções - CONMEBOL
    { name: 'Argentina', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/762.svg' },
    { name: 'Bolívia', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/763.svg' },
    { name: 'Brasil', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/764.svg' },
    { name: 'Chile', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/765.svg' },
    { name: 'Colômbia', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/766.svg' },
    { name: 'Equador', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/767.svg' },
    { name: 'Paraguai', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/768.svg' },
    { name: 'Peru', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/769.svg' },
    { name: 'Uruguai', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/771.svg' },
    { name: 'Venezuela', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/772.svg' },

    // Seleções - UEFA
    { name: 'Alemanha', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/759.svg' },
    { name: 'Bélgica', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/808.svg' },
    { name: 'Croácia', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/799.svg' },
    { name: 'Dinamarca', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/790.svg' },
    { name: 'Espanha', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/760.svg' },
    { name: 'França', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/773.svg' },
    { name: 'Holanda', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/784.svg' },
    { name: 'Inglaterra', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/770.svg' },
    { name: 'Itália', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/785.svg' },
    { name: 'Portugal', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/765.svg' },
    { name: 'Rússia', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/805.svg' },
    { name: 'Suíça', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/788.svg' },

    // Seleções - CONCACAF
    { name: 'Canadá', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/786.svg' },
    { name: 'Costa Rica', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/821.svg' },
    { name: 'Estados Unidos', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/779.svg' },
    { name: 'Honduras', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/840.svg' },
    { name: 'México', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/780.svg' },
    { name: 'Panamá', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/822.svg' },
    
    // Seleções - CAF (África)
    { name: 'África do Sul', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/801.svg' },
    { name: 'Argélia', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/812.svg' },
    { name: 'Camarões', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/794.svg' },
    { name: 'Costa do Marfim', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/795.svg' },
    { name: 'Egito', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/804.svg' },
    { name: 'Gana', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/789.svg' },
    { name: 'Marrocos', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/815.svg' },
    { name: 'Nigéria', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/776.svg' },
    { name: 'Senegal', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/803.svg' },
    { name: 'Tunísia', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/814.svg' },

    // Seleções - AFC (Ásia)
    { name: 'Arábia Saudita', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/802.svg' },
    { name: 'Austrália', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/778.svg' },
    { name: 'Coreia do Sul', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/772.svg' },
    { name: 'Irã', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/841.svg' },
    { name: 'Japão', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/766.svg' },
    { name: 'Qatar', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/8026.svg' },
];

