
export const predefinedTeams = [
    // Brasileirão Série A
    { name: 'Athletico-PR', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4289.png' },
    { name: 'Atlético-GO', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4281.png' },
    { name: 'Atlético-MG', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1766.png' },
    { name: 'Bahia', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1779.png' },
    { name: 'Botafogo', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1776.png' },
    { name: 'Corinthians', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1777.png' },
    { name: 'Criciúma', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/6698.png' },
    { name: 'Cruzeiro', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1770.png' },
    { name: 'Cuiabá', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/6684.png' },
    { name: 'Flamengo', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1780.png' },
    { name: 'Fluminense', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1765.png' },
    { name: 'Fortaleza', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4283.png' },
    { name: 'Grêmio', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1773.png' },
    { name: 'Internacional', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1769.png' },
    { name: 'Juventude', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/4291.png' },
    { name: 'Palmeiras', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1764.png' },
    { name: 'Red Bull Bragantino', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1771.png' },
    { name: 'São Paulo', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1775.png' },
    { name: 'Vasco da Gama', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1772.png' },
    { name: 'Vitória', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série A', crestUrl: 'https://crests.football-data.org/1778.png' },

    // Brasileirão Série B
    { name: 'Amazonas', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Amazonas_Futebol_Clube_2023.svg' },
    { name: 'América-MG', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1767.png' },
    { name: 'Avaí', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1774.png' },
    { name: 'Botafogo-SP', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6682.png' },
    { name: 'Brusque', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6699.png' },
    { name: 'Ceará', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4282.png' },
    { name: 'Chapecoense', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4300.png' },
    { name: 'Coritiba', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1768.png' },
    { name: 'CRB', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4299.png' },
    { name: 'Goiás', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1776.png' },
    { name: 'Guarani', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4294.png' },
    { name: 'Ituano', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6688.png' },
    { name: 'Mirassol', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/MirassolFutebolClube.png' },
    { name: 'Novorizontino', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/6692.png' },
    { name: 'Operário-PR', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Operario-pr.png' },
    { name: 'Paysandu', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Paysandu_sport_club.png' },
    { name: 'Ponte Preta', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4298.png' },
    { name: 'Santos', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1774.png' },
    { name: 'Sport Recife', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/1777.png' },
    { name: 'Vila Nova', type: 'club', countryOrConfederation: 'Brasil', league: 'Brasileirão Série B', crestUrl: 'https://crests.football-data.org/4293.png' },

    // Premier League & FA Cup
    { name: 'Arsenal', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/57.svg' },
    { name: 'Aston Villa', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/58.svg' },
    { name: 'Bournemouth', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/1044.svg' },
    { name: 'Brentford', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/402.svg' },
    { name: 'Brighton', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/397.svg' },
    { name: 'Chelsea', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/61.svg' },
    { name: 'Crystal Palace', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/354.svg' },
    { name: 'Everton', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/62.svg' },
    { name: 'Fulham', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/63.svg' },
    { name: 'Ipswich Town', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/349.svg' },
    { name: 'Leicester City', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/338.svg' },
    { name: 'Liverpool', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/64.svg' },
    { name: 'Manchester City', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/65.svg' },
    { name: 'Manchester United', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/66.svg' },
    { name: 'Newcastle United', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/67.svg' },
    { name: 'Nottingham Forest', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/345.svg' },
    { name: 'Southampton', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/340.svg' },
    { name: 'Tottenham Hotspur', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/73.svg' },
    { name: 'West Ham United', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/563.svg' },
    { name: 'Wolverhampton', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Premier League', crestUrl: 'https://crests.football-data.org/76.svg' },

    // EFL Championship (Série B Inglesa)
    { name: 'Burnley', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/328.svg' },
    { name: 'Luton Town', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/341.svg' },
    { name: 'Sheffield United', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/356.svg' },
    { name: 'Leeds United', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/347.svg' },
    { name: 'West Bromwich Albion', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/74.svg' },
    { name: 'Norwich City', type: 'club', countryOrConfederation: 'Inglaterra', league: 'Championship', crestUrl: 'https://crests.football-data.org/342.svg' },
    
    // La Liga
    { name: 'Alavés', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/263.svg' },
    { name: 'Athletic Bilbao', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/77.svg' },
    { name: 'Atlético Madrid', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/78.svg' },
    { name: 'Barcelona', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/81.svg' },
    { name: 'Celta de Vigo', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/558.svg' },
    { name: 'Espanyol', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/82.svg' },
    { name: 'Getafe', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/82.svg' },
    { name: 'Girona', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/298.svg' },
    { name: 'Las Palmas', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/279.svg' },
    { name: 'Leganés', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/299.svg' },
    { name: 'Mallorca', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/89.svg' },
    { name: 'Osasuna', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/79.svg' },
    { name: 'Rayo Vallecano', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/87.svg' },
    { name: 'Real Betis', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/90.svg' },
    { name: 'Real Madrid', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/86.svg' },
    { name: 'Real Sociedad', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/92.svg' },
    { name: 'Sevilla', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/559.svg' },
    { name: 'Valencia', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/95.svg' },
    { name: 'Valladolid', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/250.svg' },
    { name: 'Villarreal', type: 'club', countryOrConfederation: 'Espanha', league: 'La Liga', crestUrl: 'https://crests.football-data.org/94.svg' },

    // Serie A (Itália)
    { name: 'Atalanta', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/102.svg' },
    { name: 'Bologna', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/103.svg' },
    { name: 'Cagliari', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/104.svg' },
    { name: 'Como', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/471.svg' },
    { name: 'Empoli', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/107.svg' },
    { name: 'Fiorentina', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/99.svg' },
    { name: 'Genoa', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/108.svg' },
    { name: 'Hellas Verona', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/450.svg' },
    { name: 'Internazionale', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/108.svg' },
    { name: 'Juventus', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/109.svg' },
    { name: 'Lazio', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/110.svg' },
    { name: 'Lecce', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/445.svg' },
    { name: 'AC Milan', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/98.svg' },
    { name: 'Monza', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/5890.svg' },
    { name: 'Napoli', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/113.svg' },
    { name: 'Parma', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/114.svg' },
    { name: 'AS Roma', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/100.svg' },
    { name: 'Torino', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/115.svg' },
    { name: 'Udinese', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/112.svg' },
    { name: 'Venezia', type: 'club', countryOrConfederation: 'Itália', league: 'Serie A', crestUrl: 'https://crests.football-data.org/454.svg' },
    
    // Liga Portugal
    { name: 'Benfica', type: 'club', countryOrConfederation: 'Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/1903.svg' },
    { name: 'FC Porto', type: 'club', countryOrConfederation: 'Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/503.svg' },
    { name: 'Sporting CP', type: 'club', countryOrConfederation: 'Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/507.svg' },
    { name: 'SC Braga', type: 'club', countryOrConfederation: 'Portugal', league: 'Liga Portugal', crestUrl: 'https://crests.football-data.org/502.svg' },

    // Argentina
    { name: 'Boca Juniors', type: 'club', countryOrConfederation: 'Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2061.svg' },
    { name: 'River Plate', type: 'club', countryOrConfederation: 'Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2068.svg' },
    { name: 'Racing Club', type: 'club', countryOrConfederation: 'Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2067.svg' },
    { name: 'Independiente', type: 'club', countryOrConfederation: 'Argentina', league: 'Primera División', crestUrl: 'https://crests.football-data.org/2064.svg' },
    
    // MLS
    { name: 'Inter Miami CF', type: 'club', countryOrConfederation: 'EUA', league: 'MLS', crestUrl: 'https://crests.football-data.org/1607.svg' },
    { name: 'LA Galaxy', type: 'club', countryOrConfederation: 'EUA', league: 'MLS', crestUrl: 'https://crests.football-data.org/1598.svg' },
    
    // México
    { name: 'Club América', type: 'club', countryOrConfederation: 'México', league: 'Liga MX', crestUrl: 'https://crests.football-data.org/1620.svg' },
    { name: 'Chivas Guadalajara', type: 'club', countryOrConfederation: 'México', league: 'Liga MX', crestUrl: 'https://crests.football-data.org/1621.svg' },

    // Outros
    { name: 'Al-Nassr', type: 'club', countryOrConfederation: 'Arábia Saudita', league: 'Saudi Pro League', crestUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Al-Nassr_FC.svg' },
    { name: 'Al-Hilal', type: 'club', countryOrConfederation: 'Arábia Saudita', league: 'Saudi Pro League', crestUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Al-Hilal_FC_logo.svg' },

    // Seleções - CONMEBOL
    { name: 'Argentina', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/762.svg' },
    { name: 'Bolívia', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/763.svg' },
    { name: 'Brasil', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/764.svg' },
    { name: 'Chile', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/765.svg' },
    { name: 'Colômbia', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/766.svg' },
    { name: 'Equador', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/767.svg' },
    { name: 'Paraguai', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/768.svg' },
    { name: 'Peru', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/769.svg' },
    { name: 'Uruguai', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/771.svg' },
    { name: 'Venezuela', type: 'national', countryOrConfederation: 'CONMEBOL', crestUrl: 'https://crests.football-data.org/772.svg' },

    // Seleções - UEFA
    { name: 'Alemanha', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/759.svg' },
    { name: 'Bélgica', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/808.svg' },
    { name: 'Croácia', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/799.svg' },
    { name: 'Dinamarca', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/790.svg' },
    { name: 'Espanha', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/760.svg' },
    { name: 'França', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/773.svg' },
    { name: 'Holanda', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/784.svg' },
    { name: 'Inglaterra', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/770.svg' },
    { name: 'Itália', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/785.svg' },
    { name: 'Portugal', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/765.svg' },
    { name: 'Rússia', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/805.svg' },
    { name: 'Suíça', type: 'national', countryOrConfederation: 'UEFA', crestUrl: 'https://crests.football-data.org/788.svg' },

    // Seleções - CONCACAF
    { name: 'Canadá', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/786.svg' },
    { name: 'Costa Rica', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/821.svg' },
    { name: 'Estados Unidos', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/779.svg' },
    { name: 'Honduras', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/840.svg' },
    { name: 'México', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/780.svg' },
    { name: 'Panamá', type: 'national', countryOrConfederation: 'CONCACAF', crestUrl: 'https://crests.football-data.org/822.svg' },
    
    // Seleções - CAF (África)
    { name: 'África do Sul', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/801.svg' },
    { name: 'Argélia', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/812.svg' },
    { name: 'Camarões', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/794.svg' },
    { name: 'Costa do Marfim', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/795.svg' },
    { name: 'Egito', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/804.svg' },
    { name: 'Gana', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/789.svg' },
    { name: 'Marrocos', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/815.svg' },
    { name: 'Nigéria', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/776.svg' },
    { name: 'Senegal', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/803.svg' },
    { name: 'Tunísia', type: 'national', countryOrConfederation: 'CAF', crestUrl: 'https://crests.football-data.org/814.svg' },

    // Seleções - AFC (Ásia)
    { name: 'Arábia Saudita', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/802.svg' },
    { name: 'Austrália', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/778.svg' },
    { name: 'Coreia do Sul', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/772.svg' },
    { name: 'Irã', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/841.svg' },
    { name: 'Japão', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/766.svg' },
    { name: 'Qatar', type: 'national', countryOrConfederation: 'AFC', crestUrl: 'https://crests.football-data.org/8026.svg' },
];
